// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGS3dbZDMmHwCprI4o9zxqNcQiW5Oiq9A',
    appId: '1:572913481064:web:7aced0363d44895c5312dd',
    messagingSenderId: '572913481064',
    projectId: 'gocheckerbr',
    authDomain: 'gocheckerbr.firebaseapp.com',
    databaseURL: 'https://gocheckerbr-default-rtdb.firebaseio.com',
    storageBucket: 'gocheckerbr.appspot.com',
    measurementId: 'G-M7N5XMWKRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxjHFvNnGc2dEDcg1wvHyYezTcmI2Nin4',
    appId: '1:572913481064:android:82900694f624f76d5312dd',
    messagingSenderId: '572913481064',
    projectId: 'gocheckerbr',
    databaseURL: 'https://gocheckerbr-default-rtdb.firebaseio.com',
    storageBucket: 'gocheckerbr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6MOXfyUopBIlKWe04WiIMgpWH93s-OI',
    appId: '1:572913481064:ios:6256ba46f6228cc35312dd',
    messagingSenderId: '572913481064',
    projectId: 'gocheckerbr',
    databaseURL: 'https://gocheckerbr-default-rtdb.firebaseio.com',
    storageBucket: 'gocheckerbr.appspot.com',
    iosBundleId: 'com.example.gochecker',
  );
}
