// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe0cOYc90a8i9_iRBYPUVmmLj_B_PKY6Y',
    appId: '1:400838697473:web:2c0f78d5ee347a55949600',
    messagingSenderId: '400838697473',
    projectId: 'mobicheckbr',
    authDomain: 'mobicheckbr.firebaseapp.com',
    storageBucket: 'mobicheckbr.appspot.com',
    measurementId: 'G-Y3HH72CBDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgP0SlbyUSux6TZjHdnwMyJTQA6TEj37g',
    appId: '1:400838697473:android:1e7e1c655f9a559d949600',
    messagingSenderId: '400838697473',
    projectId: 'mobicheckbr',
    storageBucket: 'mobicheckbr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0a0thcmXwqLNVbgKaqC9tBPQClMG0uUY',
    appId: '1:400838697473:ios:8a87d210f3dd7ebe949600',
    messagingSenderId: '400838697473',
    projectId: 'mobicheckbr',
    storageBucket: 'mobicheckbr.appspot.com',
    iosBundleId: 'com.example.mobicheck',
  );
}
